#!/usr/bin/python
#from mod_pbxproj import XcodeProject

#project = XcodeProject.Load(ARGV[1])
import sys

writer = ""

writer += ("Argv1 = "+sys.argv[1])
#writer += "testUnity"
print sys.argv[1]
#print "test"

f = open('/Users/josh.ruis/Documents/UnityTest.txt' , 'w')
f.write(writer)
f.close()
